# Install anaconda Python stack and some other useful tools
FROM continuumio/anaconda3
RUN apt-get update
RUN apt-get install -y tar git curl wget dialog net-tools build-essential

# set conda-forge as priority conda repository
RUN conda config --add channels conda-forge

# Set up user jovyan so this image can be used e.g. on mybinder.org
ENV NB_USER jovyan
ENV NB_UID 1000
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

USER ${NB_USER}

# Install gfortran and editors
RUN conda install -y -c conda-forge compilers vim nano

# set env variables
ENV CLAW ${HOME}/clawpack-v5.6.1
ENV NETCDF4_DIR /opt/conda
ENV FC gfortran

# Install clawpack-v5.6.1:
RUN pip install --src=/${HOME}/ --user -e git+https://github.com/clawpack/clawpack.git@v5.6.1#egg=clawpack-v5.6.1

# set prompt:
RUN echo 'export PS1="jovyan $ "' >> ~/.bashrc

WORKDIR ${CLAW}
# Download the master branch of the apps repository and rename:
# (You can change `master` to a commit hash for a different version)
RUN curl -sL https://github.com/clawpack/apps/archive/master.tar.gz | tar xz
RUN mv apps-* apps

WORKDIR ${HOME}
