# Start from the clawpack v5.7.0 image that includes everything already done
# in Dockerfile_v5.7.0:
FROM clawpack/v5.7.0_dockerimage:release

USER jovyan

# upgrade to v5.7.1:

# Install clawpack-v5.7.1:
RUN pip install --src=/${HOME}/ --user -e git+https://github.com/clawpack/clawpack.git@v5.7.1#egg=clawpack-v5.7.1

ENV CLAW ${HOME}/clawpack-v5.7.1

# Install additional useful packages

RUN conda install -c conda-forge \
  xarray \
  ffmpeg

# Install additional packages useful with GeoClaw:

RUN conda install -c conda-forge \
  netcdf4 \
  netcdf-fortran \
  cartopy \
  pyproj \
  rasterio

WORKDIR ${CLAW}
# Clone the apps repository (with master checked out):
RUN git clone https://github.com/clawpack/apps.git 

WORKDIR ${HOME}

# fix a few things for git:
RUN git config --file .gitconfig core.pager more
RUN git config --file .gitconfig core.editor vim

CMD [ "/bin/bash" ]
