# Start from the clawpack v5.7.0 image that includes everything already done
# in Dockerfile_v5.7.0:
FROM clawpack/v5.7.0_dockerimage:release

USER jovyan

# Install additional packages useful with GeoClaw
# netCDF is required for some tests
RUN conda install -c conda-forge \
  xarray \
  netcdf4 \
  netcdf-fortran \
  cartopy \
  ffmpeg \
  pyproj \
  rasterio
